version: '3.8'

services:
  web:
    build: .
    container_name: perseuai-web
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - perseuai-network

networks:
  perseuai-network:
    driver: bridge 